Repository matrix-org/complement, pull requests merged in 2022-05, with the labels that each got.

#368 Add regression test when modifying events_default
  tests/csapi/power_levels_test.go
Labels: dendrite-regression

#369 Add test to make sure `/messages` behaves as expected for non-existent `room_id`'s
  tests/csapi/room_messages_test.go
Labels: synapse-regression

#382 Enable arbitrary env vars to be propagated to Complement containers
  internal/config/config.go
  internal/docker/deployer.go
Labels: enhancement
